spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.109.141.56:3306/AITeacher?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: Jac0912
    password: 012284

  security:
    jwt:
      key: 012284
      expire: 7

  data:
    redis:
      host: 47.109.141.56
      port: 6379
      connect-timeout: 5000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none


  mail:
    host: smtp.163.com
    username: 17323027745@163.com
    password: ZPcc6tEDJ475tgDX
    port: 465
    ssl:
      enabled: true

  rabbitmq:
    addresses: 47.109.141.56:5672
    username: admin
    password: 950413
    virtual-host: /

  jackson:
    time-zone: GMT+8

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: D:/A_Jac0912/temp/photo/




